services:
  frontend:
    build: frontend
    restart: unless-stopped
  db:
    build: backend/postgis/17-master
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=explorintator
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  martin:
    image: ghcr.io/maplibre/martin
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/explorintator
      - RUST_LOG=debug
    depends_on:
      - db
  api:
    build: backend/api
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=explorintator
    depends_on:
      - db
  proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - martin
      - api
